In [6]:
import numpy as np
def spiral_matrix(n):

  t= 0
  b= n-1
  l= 0
  r= n-1

  num = 1

  # creating 2d matrix of size n*n
  m= np.zeros((n,n), dtype=int)

  while t<=b and l<=b:

#traversing left to right
      for col in range(l, r+1):
          m[t,col]= num
          num +=1
      t +=1

#traversing top to bot

      for row in range(t, b+1):
          m[row,r]= num
          num +=1
      r -=1

#traversing right to left
      if t<=b:
        for col in range(r, l-1, -1 ):
          m[b,col]= num
          num +=1
        b-=1

      if l<=r:
#traversing down to top
        for row in range(b, t-1, -1 ):
          m[row,l]= num
          num +=1
      l+=1


  return m


 #example
N= 5
sprial_pattern= spiral_matrix(N)
print(sprial_pattern)

 #example

[[ 1  2  3  4  5]
 [16 17 18 19  6]
 [15 24 25 20  7]
 [14 23 22 21  8]
 [13 12 11 10  9]]
